language: php

php:
  - 5.5

env:
  matrix:
    - TYPO3_VERSION=7.6.0

mysql:
  database: travis_ci_behat
  username: root
  encoding: utf8

before_script:
  # preparing instance directories
  - mkdir -p /home/travis/build/test.instance
  # update os
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f Build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # preparing selenium
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
  - wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux32.zip && unzip chromedriver_linux32.zip && sudo mv chromedriver /usr/bin
  - java -jar selenium-server-standalone-2.48.2.jar > /dev/null &
  - sleep 5

  # require composer dependencies
  - composer update
  # - composer require heikohardt/behat-typo3-extension
  - composer require behat/mink-extension behat/mink-goutte-driver behat/mink-selenium2-driver

  # export phpunit configuration
  - export TYPO3_PATH_WEB=$PWD

  # export behat configuration
  - export BEHAT_TYPO3_DOCROOT="/home/travis/build/test.instance"
  - export BEHAT_TYPO3_DB_HOST="localhost"
  - export BEHAT_TYPO3_DB_NAME="travis_ci_behat"
  - export BEHAT_TYPO3_DB_USERNAME="root"
  - export BEHAT_TYPO3_DB_PASSWORD=""

script:
  - echo
  - echo "Processing acceptance tests"
  - >
    ./bin/behat
    -c typo3/sysext/core/Build/behat.yml;
